### PR TITLE
Fix handling 403 Forbidden Pipedrive's response

### PR DESCRIPTION
**Pull request by ORudenkoAS**

### CODE REVIEW

**Comment by ORudenkoAS** [comment]
@IsraelOrtuno Hello. Could you please, review this PR?

**Comment by IsraelOrtuno** [comment]
Ok to merge to master for now. Just wondering if this may be a breaking change for users handling exceptions before tagging a new version.

**Comment by ORudenkoAS** [comment]
> Ok to merge to master for now. Just wondering if this may be a breaking change for users handling exceptions before tagging a new version.

I think no. I just changed exception code from zero to status code if 401 and 403. In other cases it will be 0

**Comment by IsraelOrtuno** [comment]
Just released a new tag 👍

**Pull request merged**
