### PR TITLE
Update Organizations.php

### PR DESCRIPTION
**Pull request by maydin05**
it`s for Organization deals

### CODE REVIEW

**Comment by IsraelOrtuno** [comment]
@maydin05 Organizations.php already uses `ListDeals` trait which includes that method :)

**Comment by IsraelOrtuno** [comment]
https://github.com/IsraelOrtuno/pipedrive/blob/master/src/Resources/Traits/ListsDeals.php

**Comment by maydin05** [comment]
Opps sory :) I did not notice that, Thank you so much.

**Comment by IsraelOrtuno** [comment]
Yeah, maybe I should document all the methods available for each class :)

**Pull request closed without merging**
