### PR TITLE
oAuth support

### PR DESCRIPTION
**Pull request by aakarim**
Draft PR for oAuth support

## Still outstanding: 
- Updates to Readme.md
- Socialite Integration (I have actually completed this locally, I can include it in this PR or a future one).
FIXES: https://github.com/IsraelOrtuno/pipedrive/issues/37

### CODE REVIEW

**Comment by IsraelOrtuno** [comment]
We have to reconsider how this is going to be implemented as this update has breaking changes. It replaces the API token by the OAuth system, and as far as I can read in the docs, both will exist.

**Comment by aakarim** [comment]
I agree - it's not ideal to have a breaking change. 

In this version I have inserted a simple flag on construction, which would break the `new Pipedrive()` constructor in many apps. That is the major breaking change - the other change was the default API URL. This should be a simple find and replace for most. Changes to the underlying API interface should not break. We could eliminate some configuration by making the `$useOAuth` constructor parameter switch to an alternate default API URL.

Another option could be a separate constructor for the new Pipedrive oAuth apps. Something like `new PipedriveOAuth()`

**Comment by daniti** [comment]
Also, would it make sense to include part of the OAuth workflow within the library itself? (Handling refresh tokens). @IsraelOrtuno OAuth support would really be huge :)

**Comment by IsraelOrtuno** [comment]
@daniti that's my idea. Will try to get it sorted soon :)

**Comment by IsraelOrtuno** [comment]
We may create a 2.0 version for the OAuth support. 1.0 will support API access and 2.0 could play well with both.

**Pull request closed without merging**
