### PR TITLE
Add ItemSearches endpoint, deprecate SearchResults

### PR DESCRIPTION
**Pull request by simensen**
We'll want to add the property to `Pipedrive.php` as well, but we can't just yet as it would conflict with #99. But, to be fair, it might already conflict with that PR so oh well. :)

```
 * @property-read ItemSearches $itemSearches
```

If you want to do it yourself, awesome. If you want me to do it after you merge the other PRs, just let me know!

### CODE REVIEW

**Comment by simensen** [comment]
Yeah, looks like this is conflicting as expected. Happy to resolve this for you but don't want to double up on the work. :)

**Comment by simensen** [comment]
Also, had meant to include the docs link for this showing that SearchResults is indeed deprecated:

https://developers.pipedrive.com/docs/api/v1/#!/SearchResults

image

It apparently still works, so I left the code but I opted to use the `@deprecated` tag on the class instead so that people using it would get the hint.

**Comment by IsraelOrtuno** [comment]
Feel free to resolve the conflicts or I can do it myself by tomorrow :) thanks a lot!

**Comment by simensen** [comment]
Cool. Done. Got lazy and did it w/ the GitHub UI. Not sure how I feel about that. Heh.

**Comment by simensen** [comment]
Let me know if you want me to do more on this. :)

**Comment by simensen** [comment]
Thanks for the merge!

**Pull request merged**
